name: test_config
description: A test configuration file

physical_instruments:
  - uid: test_1
    name: Test Instrument 1
    class: epcomms.equipment.test.TestInstrument
  - uid: test_2
    name: Test Instrument 2
    class: epcomms.equipment.test.TestInstrument

translators:
  - metadata:
      uid: test_instrument_1_poller
      name: Test Instrument 1 Poller
      description: Poller for Test Instrument 1
    class: PollingTranslator
    physical_instrument_uid: test_1
    polling_interval: 5.0
    getter_function: get_noise
    entities:
      - setter_function: echo
        virtual_instrument:
          uid: test_vi_1
          name: Test Virtual Instrument 1
          unit: None
          description: Noise 

